spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 5000
            response-timeout: 30s
          routes:
            - id: auth-route
              uri: http://localhost:8089
              predicates:
                - Path=/api/auth/**
            - id: chat-route
              uri: http://localhost:8081
              predicates:
                - Path=/api/chat/**
              filters:
                - RewritePath=/api/chat/(?<segment>.*), /api/${segment}

jwt:
  secret: dGhpc0lzQVNlY3JldEtleUZvckpXVFNpZ25pbmcxMjM0NTY3ODkw

server:
  port: 8080

logging:
  level:
    com.ongard: DEBUG
    org.springframework.cloud.gateway: DEBUG
