spring:
  application:
    name: authentication

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-auth:5432/db-auth}
    username: ${SPRING_DATASOURCE_USERNAME:ms_usr}
    password: ${SPRING_DATASOURCE_PASSWORD:ms_usr_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        default_schema: auth

jwt:
  secret: ${JWT_SECRET:dGhpc0lzQVNlY3JldEtleUZvckpXVFNpZ25pbmcxMjM0NTY3ODkw}
  access-token-expiration: 1800
  refresh-token-expiration: 864000

bff:
  url: ${BFF_URL:http://bff:8079}

server:
  port: 8089

logging:
  level:
    com.ongard: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
