spring:
  application:
    name: ongard-chat

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-game:5432/db-game}
    username: ${SPRING_DATASOURCE_USERNAME:ms_usr}
    password: ${SPRING_DATASOURCE_PASSWORD:ms_usr_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 8081

logging:
  level:
    com.ongard: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
